### ISSUE TITLE
DVB-T2 profile and transcoding resolution

### ISSUE THREAD

**Issue by brimur** [taligentx/LiveTVH.bundle#10]
Hi @taligentx, thank you so much for the fantastic bundle you have created. I was hoping you could tell me how to direct play my DVB-T2 channels. I tried the three different channel tags in the README but the stream fails to play using them. The channels transcodes and plays fine without the tags. Maybe a tag 
These are the stream details. Its MPEG-4 AVC video and MPEG 1/2 audio according to VLC

![image](https://user-images.githubusercontent.com/8918706/27124276-72d01ff8-50e8-11e7-9e83-7be211834af7.png)

Another channel seems to be MPEG-4 AVC with AC3
![image](https://user-images.githubusercontent.com/8918706/27124251-619aeb3c-50e8-11e7-909e-4895906c9026.png)

My second question is that I have noticed all channels, even SD channels get transcoded to 1080p, at least that is what my Plex client tells me. Is this for any specific reason? I would assume it use more CPU to trancode/upscale to 1080p than the original resolution. Is it possible to add an option to transcode to the original dimensions?

Thanks again for this
B

**Comment by taligentx** [comment]
Hi @brimur,

Which Plex client are you using?  It's possible that the H264 stream isn't necessarily playable on the client (different profile level, etc) - Plex normally transcodes everything to the 4.0 Main profile, while streams can be 3.0 or 3.1 High and may not direct stream.  The first channel would use `H264-MP2` and the second would use `H264-AC3`.

You're correct about the transcoding to 1080p when you're using codec tags and not direct streaming.  The issue here is that direct streaming requires specifying the stream resolution, but Tvheadend doesn't provide this info automatically so it was originally hard set to 1080p.  For direct streaming, this doesn't matter - but if the client then decides to transcode, Plex will transcode to 1080p.

I've added support for video resolution tags to help out for this scenario in the develop branch - you can currently set the following resolution tags: `HDTV`, `720p`, `SDTV`

I've also added a preference option for direct streaming that is disabled by default since it's quite a finicky thing.

-Nikhil

**Comment by brimur** [comment]
@taligentx I am using Plex for Android on a Oneplus 3T which can direct stream almost all video types I use incl x265 (x264 is set to 5.2 in Plex client) and sometimes I also cast that to my Gen 2 Chromecast. 

> The first channel would use H264-MP2 and the second would use H264-AC3

Are these valid tags for LiveTVH? I haven't tried yet.

> you can currently set the following resolution tags: HDTV, 720p, SDTV

Thanks for this, I will try it out

**Comment by brimur** [comment]
Hi again. I tested the dev version and from looking at the way you coded it I was able to add all the various tags individually. As in, instead of H264-AAC I added H264 on its own and AAC on its own and then slected both. Some SD channels were mpeg2 video with mp2 audio so I added those two as a tag and it worked for those channels also.

For some reason though the HD channels will not work. I just see the spinning circle as if its loading. I can see in my TV server the stream is going to Plex and I can see in Plex's Now Playing the details. The HD streams are all H264 but the audio is either MP2 or AC3 and it says Video: Direct but the audio MP2 and AC3 are not supported by my Android device so it says "transcoding AC3/MP2 to AAC". But it never starts the stream. It never crashes or gives an error though, it just stays at the loading screen on the client and the stream keeps going from the TV server to Plex. The strange thing is that the H264-mp2/ac3 SD channels play fine so I changed the tags on the hd channel to the same as the SD channels but it still would not play.

**Comment by brimur** [comment]
More testing... On devices that support MP2 and/or AC3 audio the HD channels play fine.

**Comment by brimur** [comment]
@taligentx Just wanted to update. Using latest develop (21st June) I still cannot directplay HD streams. Still no errors, TVH thinks it is streaming to Plex but Plex is not delivering the stream to the client. Let me know if there is anything you want me to try. I am using tags HDTV,MP2,H264 for my DVB-T2 HD channels and HDTV,AC3,H264 for DVB-S2 HD channels but they will not play. Removing all tags or just leaving HDTV will allow the stream to be transcoded and will play. Both DVB-S2/T2 SD channels use SDTV,MP2,H264 and will direct play.
Also it seems the video and audio tags cannot be used independently, as in I cant use a tag H264 on its own to specify direct play only video and transcode audio or similarly I cant specify AAC to direct play only audio. Is this by design?
Thanks again

**Comment by taligentx** [comment]
The version of the plugin that has been in the develop branch has been pushed to master as LiveTVH 1.3 and I'm reviewing the code and the current state of the Plex plugin framework to see if there is room for improvement.  Development stalled due to the introduction of Plex's native live TV/DVR functionality and an apparently low priority by the Plex developers to fixing issues in the plugin framework (which hopefully has changed).

I'm closing out older issues, if you are still running into an issue running this plugin feel free to open a new issue with logs and I'll take a look.
