### ISSUE TITLE
This channel is not responding.

### ISSUE THREAD

**Issue by megapearl** [taligentx/LiveTVH.bundle#12]
I got regurlarly this error: "This channel is not responding."
What to do?

**Comment by petrmenzel** [comment]
I was not ablet to get this work, I am using this [IPTV.bundle](https://github.com/Cigaras/IPTV.bundle). Does not perfect. But more clear to edit it. You need only m3u file to create. You can edit icons etc.

**Comment by brimur** [comment]
Just wanted to add that I have been using LiveTVH.bundle for months and it works great for me watching local FTA (DVB-T) and freeview (DVB-S) channels from TVHeadend.

**Comment by sigma2017** [comment]
Hello, I have access to a tvheadend server and with kodi I can connect just fine and watch all the TV channels from the provided list.
I've tried this PLEX plugin also but is not working. It displays all the channels even with pictures and details but when I'm trying to watch I got this message error doesn't matter the channel:

An error occurred trying to play "Channel Name ".
shaka3015 (Media)

The plugin is installed correctly, My PLEX server is running on Centos 7.4 minimal without any issues.
What I'm doing wrong? 
Thanks in advance!

Later edit: It's working with Google Chrome, thanks :) Unfortunately is far slower until connecting and so on comparing with kodi but it works!
But the subtitle is not working, unavailable...
Any chances to make it work on a 2017 LG? 43UJ635V for example.
Thanks again

**Comment by taligentx** [comment]
The version of the plugin that has been in the develop branch has been pushed to master as LiveTVH 1.3 and I'm reviewing the code and the current state of the Plex plugin framework to see if there is room for improvement.  Development stalled due to the introduction of Plex's native live TV/DVR functionality and an apparently low priority by the Plex developers to fixing issues in the plugin framework (which hopefully has changed).

I'm closing out older issues, if you are still running into an issue running this plugin feel free to open a new issue with logs and I'll take a look.
