### ISSUE TITLE
plex transcoder process not closed

### ISSUE THREAD

**Issue by segator** [taligentx/LiveTVH.bundle#14]
Sometimes after reproduce a channel the plex trasncoder process is still "transcoding/transmuxing" so you need to close manually.
kill -9 xxxx

**Comment by tenfire** [comment]
I have the same problem.

**Comment by taligentx** [comment]
The version of the plugin that has been in the develop branch has been pushed to master as LiveTVH 1.3 and I'm reviewing the code and the current state of the Plex plugin framework to see if there is room for improvement.  Development stalled due to the introduction of Plex's native live TV/DVR functionality and an apparently low priority by the Plex developers to fixing issues in the plugin framework (which hopefully has changed).

I'm closing out older issues, if you are still running into an issue running this plugin feel free to open a new issue with logs and I'll take a look.
