### ISSUE TITLE
Broken transcoding with plex transcoder

### ISSUE THREAD

**Issue by trantoriana** [taligentx/LiveTVH.bundle#15]
Recently, I think it was a client update, the plex transcoder seems to have a problem processing any TVHeadend stream. 
Errors in the Server.log are related to dimensions:

Oct 01, 2017 12:21:28.959 [0x80c24ad00] ERROR - [Transcoder] [mpeg2video @ 0x802616a00] Invalid frame dimensions 0x0.
Oct 01, 2017 12:21:28.988 [0x80c27fb00] ERROR - [Transcoder] [mpeg2video @ 0x802616a00] Invalid frame dimensions 0x0.
Oct 01, 2017 12:21:28.988 [0x80c24ad00] ERROR - [Transcoder] [mpeg2video @ 0x802616a00] Invalid frame dimensions 0x0.

This behavior is consistent over multiple plex clients. User setup for plex is set to 'pass'.
This worked recently, but stopped working.

However, if I select a external player on android, like VLC, the transcoding works just fine as VLC bypasses the plex transcoder and directly streams from TVHeadend.

The problem must therefore be in the plex transcoder.

Anyone having similar issues ? Is this something the plugin is causing ?

Thanks, Tran

**Comment by taligentx** [comment]
The version of the plugin that has been in the develop branch has been pushed to master as LiveTVH 1.3 and I'm reviewing the code and the current state of the Plex plugin framework to see if there is room for improvement.  Development stalled due to the introduction of Plex's native live TV/DVR functionality and an apparently low priority by the Plex developers to fixing issues in the plugin framework (which hopefully has changed).

I'm closing out older issues, if you are still running into an issue running this plugin feel free to open a new issue with logs and I'll take a look.
