### ISSUE TITLE
Transcoder fails to stop when Plex Web stops playback

### ISSUE THREAD

**Issue by nuhll** [taligentx/LiveTVH.bundle#22]
Hi there,
thanks for this great plugin.

I finally was able to get everythjing working. Just some things:

1.) Android Plex (mobile) can only be played if u activate (settings -> advanced settings -> use android player)
Is this intentional? If so, it should be postet in the readme

2.) When i watch via browser (PC) over plex, tvheadend doesnt seem to get a "viewer closed stream" notice, and it "timeouts?" after 5 min.
Since i only have one LMB, this means i need to wait 5 min everytime i switch a channel... which is, ofc, very annoying. On Mobile (with android player actiavted in plex app) this is not happening, and as soon as i close, tvheadend closes the stream and i cant switch to another channel.

3.) This does not work atall on fire tv stick (the old one atleast) - dont know if newer work - i guess its also because of this "use android player" thing, but you cant activate this on the plex app for fire tv stick... <- this was the main reason for this whole thing for me :(

If you need anything, i can provide, but i guess, these errors are known?!

**Comment by zerocool9** [comment]
Hi, the new Alexa firestick dose work with an older version of plex, I have just been testing the old sticks to confirm my self but it won’t have any of it, for the first 2 seconds I get an image then it loses connection, roku works the best I think

**Comment by brimur** [comment]
Number 1 is now fixed with the new Exoplayer 2, no need to select the Android player

**Comment by nuhll** [comment]
I dont see a new version. Is it out yet?

**Comment by brimur** [comment]
I meant Plex updated their app which has a new built-in player called Exoplayer 2 which works with this plugin again. Plex broke part of their previous player back in December which prevented it working with LiveTVH. You can read more about it here...

https://plus.google.com/+AndroidDevelopers/posts/21BauLCA8aT

**Comment by brimur** [comment]
If you were referring to the Plex for Android app then yes it was released to weeks ago

**Comment by r4pt0r66** [comment]
The Amazon app store still has the old version

**Comment by nuhll** [comment]
So i guess amazon app will be updated at some point and its working again.

Any idea why on browser he doesnt recognize when i left a channel?

**Comment by brimur** [comment]
Or you could get it from the Play store? Or download the APK from the internet

**Comment by mastacheata** [comment]
Now you got me interested.
How did you manage to get the Play Store onto your AFTV?
It doesn't come with that nor with the required Google components pre-installed.

Installing APKs from third party sources is possible, but that's not everyone's thing. There are various good reasons to not enable third party sources. 

Am 17. Februar 2018 23:38:06 MEZ schrieb brimur <notifications@github.com>:
>Or you could get it from the Play store? Or download the APK from the
>internet
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/taligentx/LiveTVH.bundle/issues/22#issuecomment-366476598

-- 
Gruß, 
Benedikt Bauer

**Comment by brimur** [comment]
Sorry, I mentioned above that the first point was fixed as in Plex for Android. I don't have an Amazon device

**Comment by taligentx** [comment]
Hi @nuhll - I'm reviewing the code and the current state of the Plex plugin framework to see if there is room for improvement. Development stalled due to the introduction of Plex's native live TV/DVR functionality and an apparently low priority by the Plex developers to fixing issues in the plugin framework (which hopefully has changed).

> When i watch via browser (PC) over plex, tvheadend doesnt seem to get a "viewer closed stream" notice, and it "timeouts?" after 5 min.
Since i only have one LMB, this means i need to wait 5 min everytime i switch a channel... which is, ofc, very annoying. On Mobile (with android player actiavted in plex app) this is not happening, and as soon as i close, tvheadend closes the stream and i cant switch to another channel.

If this is only happening with one Plex client, it's likely an issue with the Plex server or client.  I'll check the plugin framework to see if there is a way to detect the stream playback status for a possible workaround, otherwise this would likely be feedback for the Plex web client developers.

**Comment by taligentx** [comment]
> 2.) When i watch via browser (PC) over plex, tvheadend doesnt seem to get a "viewer closed stream" notice, and it "timeouts?" after 5 min.
Since i only have one LMB, this means i need to wait 5 min everytime i switch a channel... which is, ofc, very annoying. On Mobile (with android player actiavted in plex app) this is not happening, and as soon as i close, tvheadend closes the stream and i cant switch to another channel.

I've verified this issue only occurs in Plex web and seems to be either a Plex web client bug or PMS bug.  I've opened up a topic for this issue and for anyone impacted by this bug I recommend commenting on this topic:

[https://forums.plex.tv/t/transcoder-fails-to-stop-when-plex-web-stops-playback-from-a-channel-stream/281848](https://forums.plex.tv/t/transcoder-fails-to-stop-when-plex-web-stops-playback-from-a-channel-stream/281848)

**Comment by taligentx** [comment]
Plex Web 3.61.1 resolves the issue - the transcoder is stopped immediately when playback is stopped and Tvheadend releases the tuner.  Switching channels with a single tuner no longer requires waiting 180s for the first transcode session to time out - hooray!

https://forums.plex.tv/t/resolved-with-plex-web-3-61-1-transcoder-fails-to-stop-when-plex-web-stops-playback-from-a-channel-plugin/281848/22

**Comment by brimur** [comment]
Thanks for the follow up I saw you had been chatting with Chuck on the Plex forum about it. Great news
